### ISSUE TITLE
Desarrollar pantalla de gestión de eventos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-open-cms#4]
Controlador
EventManager.php

Repositorio:
EloquentEvent.php

Servicio:
EventManager.php

Vista:
event-management.blade.php

Modelo:
Event.php

Prefijos:
ocms-em-, ocmsEm, ocms_Em

Tabla:
OCMS_Event

URL:

/cms/events/event-management

**Comment by alvarogarcia1010** [comment]
Listo para revisión...
Nota: Confirmar nombre de nuevos campos y que columnas serán visibles...
